authors:
  jefe:
    name: Jefe
    description: Gerant de la communauté
    avatar: https://raw.githubusercontent.com/Jefedi/los-galactique-reglement/refs/heads/main/docs/assete/author-av/IMG_0994.JPG
    slug: jefe
